version: 2
jobs:
  build:
    machine:
      node:
        version: 7
      services:
        - docker
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Bootstrap environment
          command: |
            echo 'export APP_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV
            ./scripts/ci-cd/bootstrap.sh
      - run:
          name: Build image
          command: |
            # fake the CIRCLE_SHA1 in this call to set tag to what we want
            source ./tag
            CIRCLE_SHA1=$TAG ./scripts/ci-cd/build.sh
      - deploy:
          name: publish the image
          branch: master
          command: |
            source ./tag
            ./scripts/ci-cd/setup-gcloud.sh
            CIRCLE_SHA1=$TAG ./scripts/ci-cd/publish.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global